import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const page = readFileSync(new URL('../app/pages/drama/[id]/episode/[episodeNumber].vue', import.meta.url), 'utf8')
const studioCss = readFileSync(new URL('../app/assets/studio.css', import.meta.url), 'utf8')
const apiSource = readFileSync(new URL('../app/composables/useApi.ts', import.meta.url), 'utf8')

test('episode workbench uses the approved storyboard-first video flow', () => {
  assert.match(page, /资产/)
  assert.match(page, /分镜拆分/)
  assert.match(page, /视频生成/)
  assert.match(page, /pipelineTotal/)
  assert.match(page, /const pipelineTotal = 6/)
  assert.doesNotMatch(page, /镜头设计/)
  assert.doesNotMatch(page, /pipelineProgress\s*}}\/11/)
  assert.doesNotMatch(page, /pipelineProgress\s*\/\s*11/)
  assert.doesNotMatch(page, /角色\/场景资产/)
  assert.match(page, /prod:assets/)
  assert.match(page, /prodTab === 'assets'/)
  assert.doesNotMatch(page, /script:storyboard/)
  assert.doesNotMatch(page, /分配音色/)
})

test('production includes the role and scene workspace before storyboard split', () => {
  const sidebarStart = page.indexOf('const sidebarSections')
  const sidebarEnd = page.indexOf('const activeMainStage', sidebarStart)
  assert.ok(sidebarStart > -1 && sidebarEnd > sidebarStart, 'sidebar section definition is present')
  const sidebarBlock = page.slice(sidebarStart, sidebarEnd)
  const scriptSectionStart = sidebarBlock.indexOf("id: 'script'")
  const productionSectionStart = sidebarBlock.indexOf("id: 'production'")
  const exportSectionStart = sidebarBlock.indexOf("id: 'export'")
  assert.ok(scriptSectionStart > -1, 'script sidebar section is present')
  assert.ok(productionSectionStart > scriptSectionStart, 'production sidebar section follows script')
  assert.ok(exportSectionStart > productionSectionStart, 'export sidebar section follows production')

  const scriptSection = sidebarBlock.slice(scriptSectionStart, productionSectionStart)
  const productionSection = sidebarBlock.slice(productionSectionStart, exportSectionStart)

  assert.doesNotMatch(scriptSection, /script:storyboard/)
  assert.doesNotMatch(scriptSection, /script:extract/)
  const assetsIdx = productionSection.indexOf("key: 'prod:assets'")
  const storyboardIdx = productionSection.indexOf("key: 'prod:storyboard'")
  const videosIdx = productionSection.indexOf("key: 'prod:videos'")
  assert.ok(assetsIdx > -1, 'role and scene workspace is in production')
  assert.ok(storyboardIdx > assetsIdx, 'storyboard split follows role and scene workspace')
  assert.ok(videosIdx > storyboardIdx, 'video generation follows storyboard split')
  assert.match(productionSection, /label: '资产'/)
  assert.match(productionSection, /label: '分镜拆分'/)
  assert.doesNotMatch(productionSection, /镜头设计/)
})

test('post-video dubbing is not exposed as a production step', () => {
  assert.doesNotMatch(page, /prod:dubbing/)
  assert.doesNotMatch(page, /id:\s*'dubbing'/)
  assert.doesNotMatch(page, /prodTab === 'dubbing'/)
  assert.doesNotMatch(page, /配音生成/)
  assert.doesNotMatch(page, /生成配音/)
  assert.doesNotMatch(page, /batchShotTTS/)
  assert.doesNotMatch(page, /genShotTTS/)
})

test('video composition is not exposed as a production step', () => {
  assert.doesNotMatch(page, /prod:compose/)
  assert.doesNotMatch(page, /id:\s*'compose'/)
  assert.doesNotMatch(page, /prodTab === 'compose'/)
  assert.doesNotMatch(page, /视频合成/)
  assert.doesNotMatch(page, /composeAPI/)
  assert.doesNotMatch(page, /doCompose/)
  assert.doesNotMatch(page, /batchCompose/)
  assert.doesNotMatch(page, /pollComposeStatus/)
  assert.match(page, /const pipelineTotal = 6/)
})

test('storyboard split exposes the generated shot information and prompt editor', () => {
  const storyboardStart = page.indexOf("prodTab === 'storyboard'")
  const videoStart = page.indexOf("prodTab === 'videos'", storyboardStart)
  assert.ok(storyboardStart > -1 && videoStart > storyboardStart, 'storyboard split section is present before video generation')
  const storyboardBlock = page.slice(storyboardStart, videoStart)

  assert.match(storyboardBlock, /class="storyboard-workbench"/)
  assert.match(storyboardBlock, /分镜列表/)
  assert.match(storyboardBlock, /class="storyboard-shot-card"/)
  assert.match(storyboardBlock, /class="storyboard-editor-main"/)
  assert.match(storyboardBlock, /class="sb-header-top"/)
  assert.match(storyboardBlock, /class="sb-header-fields"/)
  assert.match(storyboardBlock, /开始拆分/)
  assert.match(storyboardBlock, /重新拆分/)
  assert.match(storyboardBlock, /selectedSb/)
  assert.match(storyboardBlock, /时长/)
  assert.match(storyboardBlock, /动作/)
  assert.match(storyboardBlock, /画面描述/)
  assert.match(storyboardBlock, /对白 \/ 旁白/)
  assert.match(storyboardBlock, /氛围/)
  // 视频提示词已移至视频生成阶段，分镜拆分界面不再出现
  assert.doesNotMatch(storyboardBlock, /视频提示词/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'video_prompt'/)
  assert.match(storyboardBlock, /role-pill/)
  assert.match(storyboardBlock, /toggleStoryboardCharacter/)
  assert.match(storyboardBlock, /sceneOptions/)
  assert.match(storyboardBlock, /updateField\(selectedSb, 'scene_id'/)
  assert.doesNotMatch(storyboardBlock, /基础信息/)
  assert.doesNotMatch(storyboardBlock, /标题/)
  assert.doesNotMatch(storyboardBlock, /景别/)
  assert.doesNotMatch(storyboardBlock, /角度/)
  assert.doesNotMatch(storyboardBlock, /结果/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'title'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'shot_type'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'angle'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'result'/)
  assert.doesNotMatch(storyboardBlock, /生成首尾帧/)
  assert.doesNotMatch(storyboardBlock, /genShotFrame/)
})

test('storyboard breaker prompt only requires production fields used by the UI', () => {
  assert.match(page, /绑定角色/)
  const agentSource = readFileSync(new URL('../../backend/src/agents/index.ts', import.meta.url), 'utf8')
  const storyboardPromptStart = agentSource.indexOf('storyboard_breaker')
  const gridPromptStart = agentSource.indexOf('image_prompt_generator', storyboardPromptStart)
  const storyboardPrompt = agentSource.slice(storyboardPromptStart, gridPromptStart)

  assert.match(storyboardPrompt, /character_ids/)
  assert.match(storyboardPrompt, /scene_id/)
  assert.match(storyboardPrompt, /duration/)
  assert.match(storyboardPrompt, /action/)
  assert.match(storyboardPrompt, /description/)
  assert.match(storyboardPrompt, /dialogue/)
  assert.match(storyboardPrompt, /atmosphere/)
  assert.match(storyboardPrompt, /video_prompt/)
  assert.doesNotMatch(storyboardPrompt, /shot_type/)
  assert.doesNotMatch(storyboardPrompt, /angle/)
  assert.doesNotMatch(storyboardPrompt, /result/)
  assert.doesNotMatch(storyboardPrompt, /bgm_prompt/)
  assert.doesNotMatch(storyboardPrompt, /sound_effect/)
})

test('storyboard split shows a right-side reference asset rail', () => {
  const storyboardStart = page.indexOf("prodTab === 'storyboard'")
  const videoStart = page.indexOf("prodTab === 'videos'", storyboardStart)
  const storyboardBlock = page.slice(storyboardStart, videoStart)

  assert.match(storyboardBlock, /class="storyboard-reference-panel"/)
  assert.match(storyboardBlock, /参考素材/)
  assert.match(storyboardBlock, /getShotReferenceAssets\(selectedSb\)/)
  assert.match(storyboardBlock, /将作为视频参考图/)
  assert.match(storyboardBlock, /未生成/)
  assert.match(page, /function getShotReferenceAssets\(sb\)/)
  assert.match(page, /function getStoryboardScene\(sb\)/)
  assert.match(page, /function getStoryboardCharacters\(sb\)/)
})

test('storyboard split uses quiet white cards with a system-blue selection ring', () => {
  assert.match(page, /\.storyboard-workbench\s*\{[\s\S]*?grid-template-columns:\s*232px minmax\(0,\s*1fr\) 280px/)
  assert.match(page, /\.storyboard-shot-card\s*\{[\s\S]*?background:\s*#fff/)
  assert.match(page, /\.storyboard-shot-card\.active\s*\{[\s\S]*?border-color:\s*var\(--accent\)/)
  assert.match(page, /\.storyboard-shot-card\.active\s*\{[\s\S]*?box-shadow:\s*0 0 0 3px rgba\(0,113,227,0\.15\)/)
  assert.doesNotMatch(page, /\.storyboard-shot-card\.active\s*\{[\s\S]*?border-left-color:\s*var\(--accent\)/)
  assert.match(page, /\.storyboard-reference-panel\s*\{[\s\S]*?background:\s*var\(--surface-muted\)/)
})

test('video generation exposes a referenced task list from storyboard split', () => {
  const videoStart = page.indexOf("prodTab === 'videos'")
  const videoEnd = page.indexOf('<!-- Production Navigator -->', videoStart)
  assert.ok(videoStart > -1 && videoEnd > videoStart, 'video generation section is present')
  const videoBlock = page.slice(videoStart, videoEnd)

  assert.match(videoBlock, /class="video-task-list"/)
  assert.match(videoBlock, /AI 生成分镜/)
  assert.match(videoBlock, /doBreakdown/)
  assert.match(videoBlock, /videoTaskRows/)
  assert.match(videoBlock, /videoTaskState/)
  assert.match(videoBlock, /videoTaskStatusLabel/)
  assert.match(videoBlock, /videoTaskFailedCount/)
  assert.match(videoBlock, /参考素材/)
  assert.match(videoBlock, /task\.referenceCount/)
  assert.match(videoBlock, /genVid\(task\.storyboard\)/)
  assert.doesNotMatch(videoBlock, /缺参考图/)
  assert.doesNotMatch(videoBlock, /补参考图/)
  assert.doesNotMatch(videoBlock, /goSubStep\('script:storyboard'\)/)
})

test('video generation sends character and scene images as multimodal references', () => {
  assert.match(page, /function getShotReferenceImages\(sb\)/)
  assert.match(page, /getStoryboardCharacterIds\(sb\)/)
  assert.match(page, /scene\?\.image_url \|\| scene\?\.imageUrl/)
  assert.match(page, /char\?\.image_url \|\| char\?\.imageUrl/)
  assert.match(page, /reference_image_urls = referenceImages|reference_image_urls: referenceImages/)
  assert.doesNotMatch(page, /reference_mode: videoGenMode/)
  assert.doesNotMatch(page, /reference_mode: referenceImages\.length \? 'multiple' : 'none'/)
  assert.doesNotMatch(page, /reference_mode: 'none'/)
})

test('video generation panel keeps only reference mode with audio toggle', () => {
  const videoStart = page.indexOf("prodTab === 'videos'")
  const videoEnd = page.indexOf('<!-- Production Navigator -->', videoStart)
  const videoBlock = page.slice(videoStart, videoEnd)

  // 其他模式入口已清理
  assert.doesNotMatch(videoBlock, /videoGenMode/)
  assert.doesNotMatch(videoBlock, /文生视频/)
  assert.doesNotMatch(videoBlock, /首帧/)
  assert.doesNotMatch(videoBlock, /首尾帧/)
  assert.doesNotMatch(videoBlock, /video-frame-picker/)
  assert.doesNotMatch(page, /const videoGenMode = ref\(/)
  assert.doesNotMatch(page, /readyShotAssets|effectiveFirstFrame|uploadFrameImage/)

  // 视频提示词为面板主元素（突出展示），支持 @名字 引用参考素材，可按需 AI 生成
  assert.match(videoBlock, /video-inspector-label-hero/)
  assert.match(videoBlock, /genVideoPrompt\(selectedSb\)/)
  assert.match(videoBlock, /rows="9"/)
  assert.match(videoBlock, /用 @角色名 \/ @场景名 引用参考素材/)
  assert.match(videoBlock, /@志远、@电子厂车间/)
  assert.doesNotMatch(videoBlock, /<location>/)
  assert.doesNotMatch(videoBlock, /<role>/)

  // 多模态参考面板：参考图片/视频/音频上传 + 生成时长
  assert.match(videoBlock, /参考图片 \/ 视频 \/ 音频/)
  assert.match(videoBlock, /videoDuration/)
  assert.match(videoBlock, /生成参数/)
  assert.doesNotMatch(videoBlock, /画面比例/)
  assert.doesNotMatch(videoBlock, /生成音频/)
  assert.doesNotMatch(videoBlock, /生成模型/)
  assert.doesNotMatch(videoBlock, /videoRatio/)
  assert.doesNotMatch(videoBlock, /videoGenerateAudio/)
  assert.match(videoBlock, /uploadRefMedia\('image'\)/)
  assert.match(videoBlock, /uploadRefMedia\('video'\)/)
  assert.match(videoBlock, /uploadRefMedia\('audio'\)/)
  assert.match(videoBlock, /refImageFull/)
  assert.match(videoBlock, /\{\{ refImageUsedCount \}\}\/9/)
  assert.match(videoBlock, /videoRefVideoUrls\.length >= 3/)
  assert.match(videoBlock, /videoRefAudioUrls\.length >= 3/)

  assert.match(page, /const dramaAspectRatio = computed/)
  assert.match(page, /function genVideoPrompt\(sb\)/)
  assert.match(page, /只更新 video_prompt 字段/)
  assert.match(page, /aspect_ratio: dramaAspectRatio\.value/)
  assert.match(page, /generate_audio: true/)
  assert.match(page, /drama\.value\?\.aspect_ratio \|\| drama\.value\?\.aspectRatio \|\| '16:9'/)
  assert.match(page, /reference_video_urls: videoRefVideoUrls/)
  assert.match(page, /reference_audio_urls: videoRefAudioUrls/)
  assert.match(page, /uploadAPI\.video\(file\)/)
  assert.match(page, /uploadAPI\.audio\(file\)/)
})

test('video generation supports manual reference images up to 9 merged with scene/character images', () => {
  // 手动上传的参考图片追加到尾部（场景/角色图在前），总计 ≤9
  assert.match(page, /function getShotReferenceImages\(sb\)/)
  assert.match(page, /for \(const url of videoRefImageUrls\.value\) pushRef\(url\)/)
  assert.match(page, /refs\.length >= 9/)
  // 场景/角色素材占用额度，展示为已用数 n/9，达上限禁用
  assert.match(page, /const autoReferenceImageCount = computed/)
  assert.match(page, /const refImageUsedCount = computed/)
  assert.match(page, /const refImageFull = computed/)
  assert.match(page, /autoReferenceImageCount\.value \+ videoRefImageUrls\.value\.length/)
  assert.match(page, /refImageUsedCount\.value >= 9/)
  assert.match(page, /参考图片已达上限（含场景\/角色素材）/)
  // 参考图片状态与上传/删除逻辑
  assert.match(page, /const videoRefImageUrls = ref\(\[\]\)/)
  assert.match(page, /uploadAPI\.image\(file\)/)
  assert.match(page, /kind === 'image' \? videoRefImageUrls/)
  // 切换分镜时重置
  assert.match(page, /videoRefImageUrls\.value = \[\]/)
  // 生成时携带（reference_image_urls 由 getShotReferenceImages 提供）
  assert.match(page, /reference_image_urls: referenceImages/)
})

test('video prompt resolves @name references to numbered reference images at generation time', () => {
  // 索引映射：场景图在前、角色图在后，与 reference_image_urls 顺序一致
  assert.match(page, /function getShotReferenceIndexMap/)
  assert.match(page, /scene\?\.image_url \|\| scene\?\.imageUrl/)
  assert.match(page, /char\.name \|\| '', char\?\.image_url \|\| char\?\.imageUrl/)
  assert.match(page, /ordered\.length >= 9/)

  // @名字 → @图片N名字（N 为参考图序号）
  assert.match(page, /function resolveVideoPromptRefs/)
  assert.match(page, /@图片\$\{map\[name\]\}\$\{name\}/)
  assert.match(page, /Object\.keys\(map\)\.sort\(\(a, b\) => b\.length - a\.length\)/)

  // 生成时替换
  assert.match(page, /prompt: resolveVideoPromptRefs\(sb\)/)
})

test('production exposes the previous role and scene card workbench', () => {
  const assetStart = page.indexOf("prodTab === 'assets'")
  const storyboardStart = page.indexOf("prodTab === 'storyboard'", assetStart)
  assert.ok(assetStart > -1 && storyboardStart > assetStart, 'role and scene workbench appears before storyboard split')
  const assetBlock = page.slice(assetStart, storyboardStart)

  assert.match(assetBlock, /角色资产|角色/)
  assert.match(assetBlock, /场景图片/)
  assert.match(assetBlock, /class="character-asset-grid"/)
  assert.match(assetBlock, /class="card character-asset-card"/)
  assert.match(assetBlock, /class="card asset-card asset-click-card"/)
  assert.match(assetBlock, /doExtract/)
  assert.match(assetBlock, /开始提取/)
  assert.match(assetBlock, /重新提取/)
  assert.match(assetBlock, /角色、场景和道具会在提取后显示在这里/)
  assert.match(assetBlock, /batchCharImages/)
  assert.match(assetBlock, /batchSceneImages/)
  // 卡片展示 Agent 生成的最终提示词（角色三视图 / 场景固定视角）
  assert.match(assetBlock, /class="asset-final-prompt"/)
  assert.match(assetBlock, /最终提示词 · 三视图/)
  assert.match(assetBlock, /最终提示词 · 固定视角/)
  assert.match(assetBlock, /c\.final_prompt \|\| c\.finalPrompt/)
  assert.match(assetBlock, /s\.final_prompt \|\| s\.finalPrompt/)
  assert.match(page, /prodTab\.value = 'assets'/)
  assert.match(page, /openAssetDetail\('character'/)

  assert.doesNotMatch(page, /asset-detail-voice-panel/)
  assert.doesNotMatch(page, /角色音色/)
  assert.doesNotMatch(page, /updateCharVoice/)
  assert.doesNotMatch(page, /previewVoiceSample/)
})

test('asset detail fields are reduced to character styling and scene lighting semantics', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)

  assert.match(page, /characterVisualSummary/)
  assert.match(page, /characterStylingValue/)
  assert.match(page, /sceneLightingValue/)
  assert.match(detailBlock, /样貌/)
  assert.match(detailBlock, /妆造/)
  assert.match(detailBlock, /场景描述/)
  assert.match(detailBlock, /场景光影/)
  assert.match(detailBlock, /asset-detail-edit-grid/)
  assert.match(detailBlock, /assetDetailDraft\.appearance/)
  assert.match(detailBlock, /assetDetailDraft\.styling/)
  assert.match(detailBlock, /assetDetailDraft\.prompt/)
  assert.match(detailBlock, /assetDetailDraft\.lighting/)
  assert.match(detailBlock, /saveAssetDetail/)
  assert.doesNotMatch(detailBlock, /试听文件/)
  assert.doesNotMatch(detailBlock, /图片状态/)
  assert.doesNotMatch(detailBlock, /关联镜头/)
  assert.doesNotMatch(detailBlock, /assetDetailRelatedShots/)
  assert.doesNotMatch(detailBlock, /asset-detail-shot-list/)
  assert.doesNotMatch(detailBlock, /asset-detail-grid/)
  assert.doesNotMatch(detailBlock, /性格/)
  assert.doesNotMatch(detailBlock, /assetDetail\.item\.personality/)
})

test('asset detail dialog uses a focused preview and editor composition', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)
  assert.match(detailBlock, /class="asset-detail-shell"/)
  assert.match(detailBlock, /class="asset-detail-preview-panel"/)
  assert.match(detailBlock, /class="asset-detail-editor-panel"/)
  assert.match(detailBlock, /class="asset-detail-section-title"/)
  assert.match(detailBlock, /class="asset-detail-primary-actions"/)
  assert.match(detailBlock, /asset-detail-meta-row/)
  assert.match(detailBlock, /视觉预览/)
  assert.match(detailBlock, /编辑信息/)
})

test('character asset detail gives appearance and styling full-width editors', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)
  assert.match(detailBlock, /asset-detail-edit-grid--\$\{assetDetail\.type\}/)
  assert.match(detailBlock, /assetDetailDraft\.appearance[\s\S]*rows="6"/)
  assert.match(detailBlock, /assetDetailDraft\.styling[\s\S]*rows="6"/)
  assert.match(page, /\.asset-detail-edit-grid--character[^{]*\{[\s\S]*?grid-template-columns:\s*1fr/)
  assert.match(page, /\.asset-detail-edit-grid--character \.asset-detail-textarea[^{]*\{[\s\S]*?min-height:\s*164px/)
})

test('script flow no longer exposes a role and scene review screen', () => {
  const scriptPanelStart = page.indexOf("panel === 'script'")
  const productionPanelStart = page.indexOf("panel === 'production'", scriptPanelStart)
  assert.ok(scriptPanelStart > -1 && productionPanelStart > scriptPanelStart, 'script panel block is present')
  const scriptPanel = page.slice(scriptPanelStart, productionPanelStart)

  assert.doesNotMatch(scriptPanel, /提取角色与场景/)
  assert.doesNotMatch(scriptPanel, /extract-compact-summary/)
  assert.doesNotMatch(scriptPanel, /data-extract-tab="characters"/)
  assert.doesNotMatch(scriptPanel, /data-extract-tab="scenes"/)
  assert.doesNotMatch(scriptPanel, /class="extract-card-grid"/)
  assert.doesNotMatch(page, /class="extract-table"/)
  assert.doesNotMatch(page, /<table class="extract-table"/)
  assert.doesNotMatch(page, /script:extract/)
  const productionBlockStart = page.indexOf('const productionBlockMessage')
  const productionBlockEnd = page.indexOf('const canExport', productionBlockStart)
  assert.ok(productionBlockStart > -1 && productionBlockEnd > productionBlockStart, 'production block helpers are present')
  const productionBlockHelpers = page.slice(productionBlockStart, productionBlockEnd)
  assert.doesNotMatch(productionBlockHelpers, /开始提取/)
  assert.doesNotMatch(productionBlockHelpers, /请先提取角色与场景/)
  assert.match(page, /goProductionBlockTarget[\s\S]*prodTab\.value = 'assets'/)
})

test('scene assets expose an update API for editable detail fields', () => {
  assert.match(apiSource, /update:\s*\(id:\s*number,\s*data:\s*any\)\s*=>\s*api\.put/)
  assert.match(apiSource, /`\/scenes\/\$\{id\}`/)
})

test('shot design and first-last frame generation are removed from the workbench', () => {
  assert.doesNotMatch(page, /生成首尾帧/)
  assert.doesNotMatch(page, /生成首帧/)
  assert.doesNotMatch(page, /生成尾帧/)
  assert.doesNotMatch(page, /frameMode/)
  assert.doesNotMatch(page, /frameModeOptions/)
  assert.doesNotMatch(page, /pendingShotFrame/)
  assert.doesNotMatch(page, /genShotFrame/)
  assert.doesNotMatch(page, /batchShotFrames/)
  assert.doesNotMatch(page, /getFirstFrame/)
  assert.doesNotMatch(page, /getLastFrame/)
  assert.doesNotMatch(page, /detail-preview-grid/)
  assert.doesNotMatch(page, /shotImgCount/)
  assert.doesNotMatch(page, /openGridTool/)
  assert.doesNotMatch(page, /宫格图/)
  assert.doesNotMatch(page, /prod:shots/)
  assert.doesNotMatch(page, /prodTab === 'shots'/)
})

test('studio theme exposes the apple light palette hooks', () => {
  assert.match(studioCss, /--accent:\s*#0071e3/)
  assert.match(studioCss, /--surface-base:\s*#f5f5f7/)
  assert.match(studioCss, /--bg-base:\s*var\(--surface-base\)/)
  assert.match(studioCss, /--radius:\s*10px/)
})

test('episode workbench keeps the desktop rail at medium widths', () => {
  assert.doesNotMatch(
    page,
    /@media\s*\(max-width:\s*1240px\)\s*\{[\s\S]*?\.studio-body\s*\{[\s\S]*?grid-template-columns:\s*1fr/,
  )
  assert.match(
    page,
    /@media\s*\(max-width:\s*1080px\)\s*\{[\s\S]*?\.studio-body\s*\{[\s\S]*?grid-template-columns:\s*1fr/,
  )
})
